### ISSUE TITLE
Index error with 'get_bbox()'

### ISSUE THREAD

**Issue by GeorgeSeif** [scaelles/DEXTR-KerasTensorflow#1]
Hi there,

First off awesome repo and paper!

I was trying to run the demo code and kept getting the following error:

```
Traceback (most recent call last):
  File "demo.py", line 42, in <module>
    bbox = helpers.get_bbox(image, points=extreme_points_ori, pad=pad, zero_pad=True)
  File "/home/george/Documents/DEXTR-KerasTensorflow/helpers/helpers.py", line 160, in get_bbox
    if inds[0].shape[0] == 0:
IndexError: index 0 is out of bounds for axis 0 with size 0
```

This happened with both of the example images (dog-cat.jpg and bear.jpg). I tried clicking the points in different orders to see if that was the problem but no luck. Any ideas?

Also, I believe the `from networks import resnet` line in `classifiers.py` should be changed to `import resnet` since those two files are in the same folder. I had to change that to run the demo code.

Cheers and thanks very much!

**Comment by scaelles** [comment]
Hello,
Thanks for your comments! 
Another user reported us a similar error and in his case the problem was that he was using Python 2.7 instead of Python 3.6 (which is the one that we use). Could you check the Python version that you are using?
Cheers

**Comment by GeorgeSeif** [comment]
Ah yes, it works great with Python 3.6! I don't get the error with imports anymore and the segmentation runs cleanly.

Thanks @scaelles !
