### ISSUE TITLE
How can we fine-tune the existing model on person Dataset

### ISSUE THREAD

**Issue by humayun** [scaelles/DEXTR-KerasTensorflow#2]
Thank you for sharing interesting work. It work well on mostly images. But for my some images, it didn't segment the whole object. I am wondering if you are working on code to extend this project for fine-tuning (training) on new dataset.

Best

**Comment by scaelles** [comment]
Thanks for your interest in our work. Unfortunately, we don't have plans to re-implement the training phase in this repository as it is much more time consuming to implement than the testing phase. If you need to fine-tune, I would recommend you take a look at the [Pytorch implementation](https://github.com/scaelles/DEXTR-PyTorch).

Best
