### ISSUE TITLE
Masks on sample image are very different than results shown here

### ISSUE THREAD

**Issue by cclaan** [scaelles/DEXTR-KerasTensorflow#3]
I tried selecting the same points as the ones in the animated gif in the README, but my masks cover much less of the object.
![masks](https://user-images.githubusercontent.com/346001/38960107-d4c80152-4328-11e8-9793-a9d381f7f331.png)

Maybe it's my keras / tf version?  I'm on a mac using CPU.
Thanks

**Comment by kmaninis** [comment]
Hi, could it be that you are using Python 2.x instead of Python 3.6 which we built our code on?

**Comment by cclaan** [comment]
I am using 2.7, that could be the issue
