### ISSUE TITLE
Error 404 on download_dextr_model.sh

### ISSUE THREAD

**Issue by virajmavani** [scaelles/DEXTR-KerasTensorflow#4]
The shell script for downloading the model return a 404 error message.

**Comment by scaelles** [comment]
Hello,
I have just run the script now and it worked, maybe the server was down when you tried. Could you try again?
Thanks

**Comment by virajmavani** [comment]
Sorry! Apparently it was because I was using the bash prompt on Windows 10. It's not an issue. It runs fine now! Thank you!
